version: "3"
services:
        rockwell:
                container_name: rockwell
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - 5001:5001
                volumes:
                        - .:/usr/src/app
                restart: always


