version: "3"
services:
        rockwell:
                container_name: rockwell
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "5001:5001"
                volumes:
                        - .:/usr/src/app
        database:
                image: postgres:15.7-alpine
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_DB: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_HOST_AUTH_METHOD: trust

                        PGPORT: 5432
                volumes:
                        - rockwell_db:/var/lib/postgresql/data
                        - /scripts/Database/init.sql:/docker-entrypoint-initdb.d/init.sql
                healthcheck:
                        test: ["CMD-SHELL", "pg_isready -U postgres"]
                        interval: 1s
                        timeout: 14s
                        retries: 15
                        start_period: 2m
volumes:
        rockwell_db:



