version: "3"
services:
        rockwell:
                container_name: rockwell
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - 80:80
                        - 443:443
                        - 5000:5000
                        - 5050:5050
                        - 5051:5051
                        - 5052:5052
                volumes:
                        - .:/usr/src/app
                restart: always
        database:
                postgres:
                        image: postgres:15-alpine
                        environment:
                                POSTGRES_USER: yourusername
                                POSTGRES_PASSWORD: yourpassword
                                POSTGRES_DB: yourdatabase
                        volumes:
                                - postgres-data:/var/lib/postgresql/data
                        ports:
                                - "5432:5432"
        volumes:
                postgres-data:

