services:
        rockwell-backend:
                restart: always
                build:
                        context: ./rockwell/backend
                        dockerfile: Dockerfile 
                container_name: rockwell-backend
                ports:
                        - "5001:5001"
                environment:
                        - FLASK_APP=src
                        - FLASK_ENV=development
                volumes:
                        - ./rockwell/backend/src:/src
                depends_on:
                        - database
                command: ["poetry", "run", "flask", "run", "--host=0.0.0.0", "--port=5001"]

 #       rockwell-frontend:
 #               container_name: frontend
 #               build: 
 #                       context: ./rockwell/frontend
 #                       dockerfile: Dockerfile
 #               ports:
 #                       - "3000:3000"
 #               depends_on:
 #                       - rockwell-backend
        database:
                image: postgres:15.7-alpine
                ports:
                        - 5432:5432
                environment:
                        POSTGRES_DB: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_HOST_AUTH_METHOD: trust

                        PGPORT: 5432
                volumes:
                        - rockwell_db:/var/lib/postgresql/data
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                healthcheck:
                        test: ["CMD-SHELL", "pg_isready -U postgres"]
                        interval: 1s
                        timeout: 14s
                        retries: 10
                        start_period: 2m
volumes:
        rockwell_db:



