version: "3"
services:
        rockwell-retweet:
                container_name: rockwell-retweet
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "5001:5001"
                depends_on:
                        - authweb
                #volumes:
                        #- .:/usr/src/app
                command: ["poetry", "run", "python", "engagements/Retweet.py"]
        rockwell-authweb:
                container_name: rockwell-authweb
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - "5002:5001"
                #depends_on:
                 #       - serviceName
                command: ["poetry", "run", "python", "authorizer/twauth-web.py"]
        #rockwell-authwebv2:
        #        container_name: rockwell-authwebv2
        #        build:
        #                context: .
        #                dockerfile: Dockerfile
        #        ports:
        #                - "5003:5001"
        #        command: ["poetry", "run", "python", "authorizer/twauth-webv2.py"]
        #rockwell-dbaccess:
        #       container_name: rockwell-dbaccess
        #      build:
        #                context: .
        #                dockerfile: Dockerfile
        database:
                image: postgres:15.7-alpine
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_DB: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_HOST_AUTH_METHOD: trust

                        PGPORT: 5432
                volumes:
                        - rockwell_db:/var/lib/postgresql/data
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                healthcheck:
                        test: ["CMD-SHELL", "pg_isready -U postgres"]
                        interval: 1s
                        timeout: 14s
                        retries: 15
                        start_period: 2m
volumes:
        rockwell_db:



