services:
        rockwell-retweet:
                container_name: rockwell-retweet
                build:
                        context: .
                        dockerfile: Dockerfile
                ports:
                        - 8000:5050
                depends_on:
                        - database
                command: ["poetry", "run", "python", "engagements/Retweet.py"]
#        rockwell-authweb:
#                container_name: rockwell-authweb
#                build:
#                        context: .
#                        dockerfile: Dockerfile
 #               ports:
 #                       - "5002:5001"
 #               command: ["poetry", "run", "python", "authorizer/twauth-web.py"]
        database:
                image: postgres:15.7-alpine
                ports:
                        - "5432:5432"
                environment:
                        POSTGRES_DB: postgres
                        POSTGRES_USER: postgres
                        POSTGRES_PASSWORD: postgres
                        POSTGRES_HOST_AUTH_METHOD: trust

                        PGPORT: 5432
                volumes:
                        - rockwell_db:/var/lib/postgresql/data
                        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
                healthcheck:
                        test: ["CMD-SHELL", "pg_isready -U postgres"]
                        interval: 1s
                        timeout: 14s
                        retries: 10
                        start_period: 2m
volumes:
        rockwell_db:



